export const FETCH_CUSTOM_RECIPE_SUCCESS = "FETCH_CUSTOM_RECIPE_SUCCESS";
export const FETCH_CUSTOM_RECIPE_START = "FETCH_CUSTOM_RECIPE_START";
export const FETCH_CUSTOM_RECIPE_FAILED = "FETCH_CUSTOM_RECIPE_FAILED";

export const CLEAR_ADD_FORM="CLEAR_ADD_FORM";

export const ADD_CUSTOM_RECIPE_SUCCESS = "ADD_CUSTOM_RECIPE_SUCCESS";
export const ADD_CUSTOM_RECIPE_START = "ADD_CUSTOM_RECIPE_START";
export const ADD_CUSTOM_RECIPE_FAILED = "ADD_CUSTOM_RECIPE_FAILED";

export const FETCH_USER_RECIPES_SUCCESS = "FETCH_USER_RECIPES_SUCCESS";
export const FETCH_USER_RECIPES_FAILED = "FETCH_USER_RECIPES_FAILED";
export const FETCH_USER_RECIPES_START = "FETCH_USER_RECIPES_START";

export const FETCH_USER_DATA_START = "FETCH_USER_DATA_START";
export const FETCH_USER_DATA_SUCCESS = "FETCH_USER_DATA_SUCCESS";
export const FETCH_USER_DATA_FAILED = "FETCH_USER_DATA_FAILED";

export const UPDATE_USER_DATA_START="UPDATE_USER_DATA_START";
export const UPDATE_USER_DATA_SUCCESS="UPDATE_USER_DATA_SUCCESS";
export const UPDATE_USER_DATA_FAILED="UPDATE_USER_DATA_FAILED";
	

export const UPDATE_RECIPE= "UPDATE_RECIPE";
export const DELETE_RECIPE= "DELETE_RECIPE";


export const FETCH_SEARCH_RECIPES_SUCCESS = "FETCH_SEARCH_RECIPES_SUCCESS";
export const FETCH_SEARCH_RECIPES_FAILED = "FETCH_SEARCH_RECIPES_FAILED";
export const FETCH_SEARCH_RECIPES_START = "FETCH_SEARCH_RECIPES_START";

export const FETCH_MORE_SEARCH_RECIPES_SUCCESS = "FETCH_MORE_SEARCH_RECIPES_SUCCESS";
export const FETCH_MORE_SEARCH_RECIPES_FAILED = "FETCH_MORE_SEARCH_RECIPES_FAILED";
export const FETCH_MORE_SEARCH_RECIPES_START = "FETCH_MORE_SEARCH_RECIPES_START";

export const FETCH_SEARCH_RECIPE_SUCCESS = "FETCH_SEARCH_RECIPE_SUCCESS";
export const FETCH_SEARCH_RECIPE_FAILED = "FETCH_SEARCH_RECIPE_FAILED";
export const FETCH_SEARCH_RECIPE_START = "FETCH_SEARCH_RECIPE_START";

export const RESET_SEARCH_RECIPES = "RESET_SEARCH_RECIPES";

export const AUTH_START = "AUTH_START";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_FAILED = "AUTH_FAILED";

export const LOGOUT = "LOGOUT";

export const NEW_USER = "NEW_USER";